name: GDSII Flow
on: [push]

jobs:
  openlane_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OpenLane 2
        uses: theopenlane/setup-openlane@v1
        with:
          # This ensures the environment is actually active
          openlane_version: latest

      - name: Run Hardening
        run: |
          openlane --config ./openlane/config.json --pdk sky130A
          
      - name: Upload GDSII
        uses: actions/upload-artifact@v4
        with:
          name: RV32I_GDSII
          # OpenLane 2 puts everything in a timestamped run folder
          path: runs/*/final/gds/*.gds
