name: GDSII Flow
on: [push]

jobs:
  openlane_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run OpenLane
        run: |
          # We mount your repo to /work and run the tool from its internal home
          docker run --rm \
            -v $(pwd):/work \
            -w /work \
            efabless/openlane:latest \
            /openlane/flow.tcl -design ./openlane -overwrite

      - name: Upload GDSII
        uses: actions/upload-artifact@v4
        with:
          name: RV32I_GDSII
          path: openlane/runs/*/results/final/gds/*.gds
