name: GDSII Flow
on: [push]

jobs:
  openlane_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run OpenLane 2
        run: |
          docker run --rm \
            -v $(pwd):/work \
            -w /work \
            efabless/openlane:latest \
            python3 -m openlane --config ./openlane/config.json --pdk sky130A
          
      - name: Upload GDSII
        uses: actions/upload-artifact@v4
        with:
          name: RV32I_GDSII
          # OpenLane 2 output paths are slightly different, this wildcard finds it:
          path: runs/*/final/gds/*.gds
